# theme: jekyll-theme-so-simple
remote_theme: "mmistakes/so-simple-theme@3.2.0"
title: Jacob Wallace
# description: I am a developer specializing in TypeScript and the JavaScript ecosystem.
# show_downloads: true